### PR TITLE
Restore legacy content. Fixes #27

### LINKED ISSUE #27: Make sure links to legacy content still work after we migrate to new docs

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by jcoyne** [comment]
@jenlindner I think that's because this depends on #50 being merged first.

**Comment by jenlindner** [comment]
I commented in the other PR, but should have here -- we can't kill this content until we've replaced it. It's not great and probably should go somewhere else, maybe into a legacy tutorials section, but the WG committed to keeping it alive in some form when we took over its url.

**Comment by jcoyne** [comment]
@jenlindner this PR isn't killing the content, it's restoring it to it's former glory.

**Comment by jenlindner** [comment]
My bad! Heh, thanks. I'm going to link it from the side nav.

**Comment by jenlindner** [comment]
I moved the deeper dive and touring index files to page directory and assets to asset directories, works with side navigation.

**Comment by jcoyne** [comment]
I think it now looks bad again. The javascript isn't working.  I'm also disappointed you didn't put your changes up for review as described in the contributing guide: https://github.com/projecthydra/projecthydra.github.io/blob/master/CONTRIBUTING.md#submitting-changes

**Pull request merged**
